### ISSUE TITLE
Any of those PCB's still available?

### ISSUE THREAD

**Issue by mroote** [Jens-Si/Taranis-X9D_USB-C-Mod#1]
Nicely done adding USB-C to the trusty Taranis! I'd be interested in one of the PCB's if you have any available still, my contact info is in my Github profile.

Thanks!

**Comment by Jens-Si** [comment]
Yes, i still have a few left. I have sent you an email.

**Comment by sl1pkn07** [comment]
hi. great project!!

 still available?

greetings
