### ISSUE TITLE
X9D SE 2019

### ISSUE THREAD

**Issue by Difo96** [Jens-Si/Taranis-X9D_USB-C-Mod#2]
I want to made the same mod on my Taranis X9D Plus SE 2019, the issue is that the 2019 verion has the USB and the two Jacks on the same PCB, can i use your mod simply moving the USB-C PCB in another location, remove the original Mini USB connector and use four wires to connect your USB-C PCB to the original PCB?!
P.S. in the 2019 version the USB connector is also used for battery charging.

**Comment by Jens-Si** [comment]
i don't have this radio, so this is just speculation. It shoud be possible if the charging only uses 5V and no QC or PD.
Maybe connect the USB-C and test everything bevore you remove the original one.

**Comment by Difo96** [comment]
Ehi! Hi! At the end I bought a new USB board to test how it works, i
studied a bit and did a lot of research so I was able to design a new one
with a USB-C port and a connector for a secondary USB-C port.
From the board I have 5 volts when it is plugged to the USB charger so it
is not a QC or PD device, I already have the new boards but I'm waiting to
install them because I want to make a video about it.

Thanks for your reply.
Matteo.

Il giorno mer 21 dic 2022 alle ore 08:50 El_Burrito <
***@***.***> ha scritto:
