### ISSUE TITLE
Ripped 5V pad

### ISSUE THREAD

**Issue by EcN000** [Jens-Si/Taranis-X9D_USB-C-Mod#3]
I ripped my 5V pad off on my taranis board...is 5V needed in order for this to function? Any idea where I can tap for 5V?

**Comment by Jens-Si** [comment]
I don’t remember the 5V being used for anything. So it should not be a problem.

**Comment by EcN000** [comment]
Okay thanks, because I do see your PCB connecting 5V...will re-assemble and
see. Thank you for your designs btw.

**Comment by Jens-Si** [comment]
Test the USB-Storage and USB-Controler funktion. If something is not working, then you can solder a wire to the 5. pad here:
![trace](https://user-images.githubusercontent.com/11742377/208854117-a5d5a910-506e-4701-b6bc-a6a404e08bef.jpg)

**Comment by EcN000** [comment]
Tried without 5V and it didn't work. Hooked it up to the 5V worked! thank
you!
